#!/usr/bin/env bash
# Script to run ROVIOLI and creating a map from a Rosbag.
# Usage: kiwicampus_mapping <output save folder> <rosbag path> [<additional rovioli flags>]

LOCALIZATION_MAP_OUTPUT=$1
ROSBAG=$2
NCAMERA_CALIBRATION="$ROVIO_CONFIG_DIR/ncamera_mynt_eye.yaml"
IMU_PARAMETERS_MAPLAB="$ROVIO_CONFIG_DIR/imu_mynt_eye.yaml"
REST=$@

rosrun rovioli rovioli \
  --alsologtostderr=1 \
  --v=2 \
  --ncamera_calibration=$NCAMERA_CALIBRATION  \
  --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB \
  --datasource_type="rosbag" \
  --save_map_folder="$LOCALIZATION_MAP_OUTPUT" \
  --optimize_map_to_localization_map=false \
  --rovio_enable_frame_visualization=false \
  # --vio_rosbag_realtime_playback_rate=2.0 \
  --map_builder_save_image_as_resources=false \
  --datasource_rosbag=$ROSBAG $REST