#!/usr/bin/env bash
# Script to run ROVIOLI and perform online localization.
# Usage: kiwicampus_online_localization <localization map path> <output save folder> <rosbag path> [<additional rovioli flags>]

LOCALIZATION_MAP_INPUT=$1
LOCALIZATION_MAP_OUTPUT=$2
NCAMERA_CALIBRATION="$ROVIO_CONFIG_DIR/ncamera_mynt_eye.yaml"
IMU_PARAMETERS_MAPLAB="$ROVIO_CONFIG_DIR/imu_mynt_eye.yaml"
REST=$@

rosrun rovioli rovioli \
  --alsologtostderr=1 \
  --v=2 \
  --ncamera_calibration=$NCAMERA_CALIBRATION  \
  --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB \
  --publish_debug_markers \
  --datasource_type="rostopic" \
  --optimize_map_to_localization_map=false \
  --vio_localization_map_folder=$LOCALIZATION_MAP_INPUT \
  --save_map_folder=$LOCALIZATION_MAP_OUTPUT \
  --rovio_enable_frame_visualization=false \
  --rovioli_visualize_map=true \
  --map_builder_save_image_as_resources=false $REST